apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: python-argo-spark-
  namespace: argo-workflows
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: dag 
    templates:
    - name: dag 
      dag:
        tasks:
        - name: download-job
          template: download-job 
        - name: bike-type
          template: bike-type
          depends: "download-job"
    - name: download-job
      container:
        image: basan12/download-data
        command: [python]
        args: ["download_file.py"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: download-dataset-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: download-dataset-secret
                key: AWS_SECRET_KEY
          - name: KAGGLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: download-dataset-secret
                key: KAGGLE_USERNAME              
          - name: KAGGLE_KEY
            valueFrom:
              secretKeyRef:
                name: download-dataset-secret
                key: KAGGLE_KEY
          - name: AWS_REGION_NAME
            valueFrom:
              configMapKeyRef:
                name: download-dataset-config
                key: AWS_REGION_NAME
          - name: AWS_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: download-dataset-config
                key: AWS_BUCKET_NAME
          - name: IDENTIFIER
            valueFrom:
              configMapKeyRef:
                name: download-dataset-config
                key: IDENTIFIER
    - name: bike-type
      resource:
        action: create
        successCondition: status.applicationState.state == COMPLETED
        failureCondition: status.applicationState.state == FAILED
        manifest: |
          apiVersion: sparkoperator.k8s.io/v1beta2
          kind: SparkApplication
          metadata: 
            generateName: spark-bike-type-
            namespace: default
          spec:
            type: Python
            sparkVersion: "3.1.1"
            mode: cluster
            image: basan12/biketypejob
            imagePullPolicy: IfNotPresent
            mainApplicationFile: "local:///app/bikeTypeJob.py"
            hadoopConf:
              "fs.s3a.impl": org.apache.hadoop.fs.s3a.S3AFileSystem
              "com.amazonaws.services.s3.enableV4": "true"
              "fs.s3a.aws.credentials.provider": org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
            restartPolicy:
              type: Never
            sparkConf:
              spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.1.1,org.apache.hadoop:hadoop-common:3.1.1,com.amazonaws:aws-java-sdk:1.11.1034"
              spark.jars.ivy: "/tmp/ivy"
              spark.jars.repositories: "https://repo1.maven.org/maven2/"
            driver:
              coreRequest: "200m"
              coreLimit: "99999"
              memory: "1024m"
              serviceAccount: spark-driver
              env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: download-dataset-secret
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: download-dataset-secret
                    key: AWS_SECRET_KEY
              - name: FILE_LOCATION
                valueFrom:
                  configMapKeyRef:
                    name: download-dataset-config
                    key: FILE_LOCATION
              labels:
                version: 3.1.1
            executor:
              coreRequest: "200m"
              coreLimit: "99999"
              instances: 2
              memory: "1024m"
              env:
              - name: FILE_LOCATION
                valueFrom:
                  configMapKeyRef:
                    name: download-dataset-config
                    key: FILE_LOCATION
              labels:
                version: 3.1.1
                
                
                
                

        